#!/usr/bin/env python3
"""Research gap analyzer.

Ranks under-saturated taxonomy cells (category/subcategory) by an
*opportunity score* that joins thinness with 12-month momentum: a thin cell
that is also surging (lots of recent output) is more promising white space
than a thin cell that is flat.

    gap_score(cell) = thinness_weight * (1 - count / category_avg)
                    + momentum_weight * normalized_12m_growth(cell)
                    + floor_bonus          if count <= gap_floor

Inputs:  statistics.json (window metadata), papers.yaml, config/taxonomy.yaml.
Output:  ranked gap table on stdout, and — with ``--write-doc`` —
         docs/research/gap_analysis.md (generated, read-only, deterministic).

Usage:
    python3 tools/research_gap_analyzer.py
    python3 tools/research_gap_analyzer.py --top 20 --write-doc
"""

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
import research_config  # noqa: E402  (shared scripts/research_config.py)

GAP_REPORT = REPO / "docs" / "research" / "gap_analysis.md"
FOOTER = "Generated by `tools/research_gap_analyzer.py` — do not edit by hand."
DEFAULT_FLOOR_BONUS = 0.15
MAX_PAPERS_PER_CELL = 5

# Rich fallback names for ids the corpus uses but config/taxonomy.yaml has not
# caught up with yet (kept in sync with tools/landscape_analyzer.py).
_CURATED_CATEGORY = {
    "tooling": "Tools, Platforms & AI Tutors",
}

_CURATED_SUBCATEGORY = {
    "systems": "Systems & Technology",
    "review": "Reviews & Surveys",
    "evaluation": "Evaluation & Benchmarks",
    "development": "Development & Implementation",
}


def _cat_disp(cfg, cat_id: str) -> str:
    name = research_config.category_display(cfg, cat_id)
    if name != cat_id:
        return name
    return _CURATED_CATEGORY.get(cat_id, cat_id.replace("-", " ").title())


def _sub_disp(cfg, sub_id: str) -> str:
    name = research_config.subcategory_display(cfg, sub_id)
    if name != sub_id:
        return name
    return _CURATED_SUBCATEGORY.get(sub_id, sub_id.replace("-", " ").title())


def load_papers() -> list:
    with open(REPO / "papers.yaml", encoding="utf-8") as f:
        return (yaml.safe_load(f) or {}).get("papers", []) or []


def load_stats() -> dict:
    path = REPO / "statistics.json"
    if not path.exists():
        sys.exit(
            "statistics.json not found — run the statistics step first "
            "(`python3 scripts/analysis/generate_analysis.py`)"
        )
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def window_start(stats: dict) -> str:
    """Start of the 12-month analysis window, from statistics.json metadata."""
    ws = (stats.get("metadata") or {}).get("analysis_window") or {}
    return ws.get("last_12m_start") or "0000-00"


def collect_cells(papers: list, ws: str) -> dict:
    """Per-cell totals, last-12m counts, and papers (newest first)."""
    cells = defaultdict(
        lambda: {"count": 0, "recent": 0, "papers": []}
    )
    for e in papers:
        cat, sub = e.get("category"), e.get("subcategory")
        if not cat or not sub:
            continue
        cell = f"{cat}/{sub}"
        info = cells[cell]
        info["count"] += 1
        date = e.get("date", "") or ""
        if date and date >= ws:
            info["recent"] += 1
        info["papers"].append(
            {"title": e.get("title", ""), "date": date, "url": e.get("url", "")}
        )
    for info in cells.values():
        info["papers"].sort(key=lambda p: p["date"], reverse=True)
    return dict(cells)


def category_stats(papers: list) -> tuple:
    """Per-category paper totals and the average count of a populated cell."""
    totals = defaultdict(int)
    subcats = defaultdict(set)
    for e in papers:
        cat, sub = e.get("category"), e.get("subcategory")
        if not cat or not sub:
            continue
        totals[cat] += 1
        subcats[cat].add(sub)
    avgs = {
        cat: totals[cat] / max(1, len(subcats[cat]))
        for cat in totals
    }
    return totals, avgs


def compute_gaps(cells: dict, cat_avgs: dict, thin_w: float,
                 mom_w: float, gap_floor: int, floor_bonus: float) -> list:
    rows = []
    for cell, info in cells.items():
        cat, sub = cell.split("/", 1)
        count, recent = info["count"], info["recent"]
        prior = count - recent
        avg = cat_avgs.get(cat) or 1.0
        thinness = max(0.0, 1.0 - count / avg) if avg else 0.0
        norm_growth = (
            min(1.0, recent / prior) if prior > 0 else (1.0 if recent > 0 else 0.0)
        )
        growth_pct = (
            (recent / prior - 1.0) * 100.0 if prior > 0
            else (100.0 if recent > 0 else 0.0)
        )
        bonus = floor_bonus if count <= gap_floor else 0.0
        raw = thin_w * thinness + mom_w * norm_growth + bonus
        rows.append({
            "cell": cell, "category": cat, "subcategory": sub, "count": count,
            "cat_avg": round(avg, 1), "recent": recent, "growth_pct": round(growth_pct, 1),
            "score": round(min(100.0, raw * 100.0), 1),
        })
    return sorted(rows, key=lambda r: (-r["score"], r["count"], r["cell"]))


def why_note(row: dict) -> str:
    if row["subcategory"] in ("evaluation",):
        return "Evaluation evidence — a core target of this program's research plan."
    if row["subcategory"] in ("development",):
        return "Implementation/development evidence — a core target of this program's research plan."
    if row["count"] <= row["cat_avg"] and row["growth_pct"] >= 100:
        return "Thin for its category yet surging in the last 12 months."
    if row["count"] <= row["cat_avg"]:
        return "Thin for its category (below the category cell average)."
    return "Below the opportunity threshold but recently active."


def render_markdown(rows: list, cells: dict, top: int, thin_w: float,
                    mom_w: float, gap_floor: int, floor_bonus: float) -> str:
    cfg = research_config.load_config()
    lines = []
    lines.append("# Research Gap Analysis")
    lines.append("")
    lines.append(
        "Ranked under-saturated taxonomy cells by opportunity score = "
        f"thinness × {thin_w} + 12-month momentum × {mom_w} "
        f"+ floor bonus ({floor_bonus}) for cells with ≤ {gap_floor} papers. "
        "Thin-and-surging cells rank highest — they are where the program's "
        "white space is both real and active."
    )
    lines.append("")
    lines.append(f"## Top {top} Gap Cells")
    lines.append("")
    lines.append("| Rank | Cell | Papers | Cat Avg | 12m New | 12m Growth | Score |")
    lines.append("|-----:|------|-------:|--------:|--------:|-----------:|------:|")
    for i, r in enumerate(rows[:top], 1):
        lines.append(
            f"| {i} | `{r['cell']}` | {r['count']} | {r['cat_avg']} "
            f"| {r['recent']} | {r['growth_pct']:+.0f}% | {r['score']} |"
        )
    lines.append("")
    lines.append(f"## Detailed Cells (top {top})")
    lines.append("")
    for r in rows[:top]:
        cat, sub = r["cell"].split("/", 1)
        lines.append(
            f"### {_cat_disp(cfg, cat)} / "
            f"{_sub_disp(cfg, sub)} (`{r['cell']}`)"
        )
        lines.append("")
        lines.append(
            f"- **Papers:** {r['count']} (category cell avg {r['cat_avg']}) — "
            f"{r['recent']} published in the last 12 months ({r['growth_pct']:+.0f}%)."
        )
        lines.append(f"- **Why a gap:** {why_note(r)}")
        lines.append("- **Representative papers (newest first):**")
        for p in cells[r["cell"]]["papers"][:MAX_PAPERS_PER_CELL]:
            title = p["title"].replace("|", "\\|").replace("\n", " ")
            lines.append(
                f"  - **{title}** ({p['date'] or 'undated'})"
                + (f" — <{p['url']}>" if p.get("url") else "")
            )
        lines.append("")
    empty = [c for c, i in cells.items() if i["count"] == 0]
    if empty:
        lines.append(f"## Fully Empty Cells ({len(empty)})")
        lines.append("")
        lines.append("No papers at all — the discovery pipeline should target these first:")
        lines.append("")
        lines.append(", ".join(f"`{c}`" for c in sorted(empty)))
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(FOOTER)
    lines.append("")
    return "\n".join(lines)


def render_table(rows: list, top: int) -> str:
    out = ["Research gap score (0-100) — thinness + 12-month momentum:",
           f"{'Rank':>4}  {'Score':>6}  {'Papers':>6}  {'12m':>4}  {'Growth':>7}  Cell",
           f"{'':4}  {'':6}  {'':6}  {'':4}  {'':7}  ----"]
    for i, r in enumerate(rows[:top], 1):
        out.append(
            f"{i:>4}  {r['score']:>6.1f}  {r['count']:>6}  {r['recent']:>4}  "
            f"{r['growth_pct']:>+6.0f}%  {r['cell']}"
        )
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top", type=int, default=20, help="number of top cells (default 20)")
    parser.add_argument("--thinness-weight", type=float, default=0.6,
                        help="weight of the thinness term (default 0.6)")
    parser.add_argument("--momentum-weight", type=float, default=0.4,
                        help="weight of the momentum term (default 0.4)")
    parser.add_argument("--gap-floor", type=int, default=5,
                        help="cells with <= this many papers get the floor bonus (default 5)")
    parser.add_argument("--floor-bonus", type=float, default=DEFAULT_FLOOR_BONUS,
                        help="bonus added to very thin cells (default 0.15)")
    parser.add_argument("--write-doc", action="store_true",
                        help="write docs/research/gap_analysis.md and print a short summary")
    args = parser.parse_args()

    stats = load_stats()
    papers = load_papers()
    ws = window_start(stats)
    cells = collect_cells(papers, ws)
    cat_totals, cat_avgs = category_stats(papers)
    rows = compute_gaps(cells, cat_avgs, args.thinness_weight,
                        args.momentum_weight, args.gap_floor, args.floor_bonus)

    if args.write_doc:
        doc = render_markdown(rows, cells, args.top, args.thinness_weight,
                              args.momentum_weight, args.gap_floor, args.floor_bonus)
        GAP_REPORT.parent.mkdir(parents=True, exist_ok=True)
        GAP_REPORT.write_text(doc, encoding="utf-8")
        print(f"Wrote {GAP_REPORT.relative_to(REPO)} "
              f"({args.top} cells, {len(cells)} cells analyzed)")
    else:
        print(render_table(rows, args.top))


if __name__ == "__main__":
    main()
